---
name: Checks

# Run when push 
on: [push]

jobs:
  # test lint
  test-lint:
    name: Test and Lint
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # the check out is to make the code available to the next steps
      - name: Checkout
        uses: actions/checkout@v2

      # the test
      - name: Test
        run: docker-compose run --rm app sh -c "python manage.py test"
        